---
apiVersion: v1
kind: ConfigMap
metadata:
  name: conf
data:
  repositories.yaml: |-
    mavenReposAndUrls:
      3rdparty-maven: https://repo1.maven.org/maven2/
      3rdparty-maven-gradle-plugins: https://plugins.gradle.org/m2/
---
apiVersion: v1
data:
  user: aGVsbG8=
  pass: d29ybGQ=
kind: Secret
metadata:
  name: creds
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: yaam
spec:
  rules:
    - host: yaam.some-domain
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: yaam
                port:
                  number: 25213
---
apiVersion: v1
kind: Service
metadata:
  name: yaam
  labels:
    app: yaam
spec:
  ports:
    - port: 25213
      name: yaam
  clusterIP: None
  selector:
    app: yaam
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: yaam
spec:
  maxReplicas: 10
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 80
          type: Utilization
      type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: yaam
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: yaam
  labels:
    app: yaam
spec:
  serviceName: yaam
  selector:
    matchLabels:
      app: yaam
  replicas: 2
  template:
    metadata:
      labels:
        app: yaam
    spec:
      containers:
        - name: yaam
          env:
            - name: YAAM_USER
              valueFrom:
                secretKeyRef:
                  name: creds
                  key: user
            - name: YAAM_PASS
              valueFrom:
                secretKeyRef:
                  name: creds
                  key: pass
          image: utrecht/yaam:0.2.1
          readinessProbe:
            tcpSocket:
              port: 25213
            initialDelaySeconds: 3
            periodSeconds: 2
          livenessProbe:
            tcpSocket:
              port: 25213
            initialDelaySeconds: 9
            periodSeconds: 4
          resources:
            limits:
              memory: 16Mi
              cpu: 50m
            requests:
              memory: 1Mi
              cpu: 1m
          ports:
            - containerPort: 25213
              name: yaam
          volumeMounts:
            - name: conf
              mountPath: /opt/yaam/.yaam/conf
            - name: repositories
              mountPath: /opt/yaam/.yaam/repositories
      volumes:
        - name: conf
          configMap:
            name: conf
        - name: repositories
          emptyDir: {}
