---
apiVersion: v1
kind: Namespace
metadata:
  name: yaam
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: conf
data:
  config.yml: |-
    ---
    caches:
      apt:
        3rdparty-ubuntu-nl-archive:
          url: http://nl.archive.ubuntu.com/ubuntu/
      maven:
        3rdparty-maven:
          url: https://repo.maven.apache.org/maven2/
        3rdparty-maven-gradle-plugins:
          url: https://plugins.gradle.org/m2/
        3rdparty-maven-spring:
          url: https://repo.spring.io/release/
        other-nexus-repo-releases:
          url: https://some-nexus/repository/some-repo/
          user: some-user
          pass: some-pass
      npm:
        3rdparty-npm:
          url: https://registry.npmjs.org/
    groups:
      maven:
        hello:
          - maven/releases
          - maven/3rdparty-maven
          - maven/3rdparty-maven-gradle-plugins
          - maven/3rdparty-maven-spring
          - maven/other-nexus-repo-releases
    publications:
      generic:
        - something
      maven:
        - releases
      npm:
        - 3rdparty-npm
---
apiVersion: v1
data:
  user: aGVsbG8=
  pass: d29ybGQ=
kind: Secret
metadata:
  name: creds
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: yaam
spec:
  rules:
    - host: yaam.some-domain
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: yaam
                port:
                  number: 25213
---
apiVersion: v1
kind: Service
metadata:
  name: yaam
  labels:
    app: yaam
spec:
  ports:
    - port: 25213
      name: yaam
  selector:
    app: yaam
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: yaam
spec:
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30
  maxReplicas: 10
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 90
          type: Utilization
      type: Resource
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: yaam
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: yaam
  labels:
    app: yaam
spec:
  serviceName: yaam
  selector:
    matchLabels:
      app: yaam
  replicas: 2
  template:
    metadata:
      labels:
        app: yaam
    spec:
      containers:
        - name: yaam
          env:
            - name: YAAM_DEBUG
              value: 'true'
            - name: YAAM_HOST
              value: yaam.some-domain
            - name: YAAM_USER
              valueFrom:
                secretKeyRef:
                  name: creds
                  key: user
            - name: YAAM_PASS
              valueFrom:
                secretKeyRef:
                  name: creds
                  key: pass
          image: utrecht/yaam:v0.5.1
          livenessProbe:
            httpGet:
              path: /status
              port: 25213
          readinessProbe:
            httpGet:
              path: /status
              port: 25213
          resources:
            limits:
              cpu: 480m
              memory: 30Mi
            requests:
              cpu: 96m
              memory: 5Mi
          ports:
            - containerPort: 25213
              name: yaam
          volumeMounts:
            - name: conf
              mountPath: /opt/yaam/.yaam
            - name: repositories
              mountPath: /opt/yaam/.yaam/repositories
      volumes:
        - name: conf
          configMap:
            name: conf
        - name: repositories
          persistentVolumeClaim:
            claimName: repositories
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: repositories
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /repositories/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: repositories
spec:
  volumeName: repositories
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
