---
name: Golang
'on':
  # required by gomod-go-version-updater to trigger this action once pr has
  # been reviewed
  pull_request_review:
    types: [submitted]
  push:
jobs:
  mcvs-golang-action:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: schubergphilis/mcvs-golang-action@v0.6.1
