---
name: Hadolint
'on': push
jobs:
  dive:
    runs-on: ubuntu-latest
    name: Analyze image using hadolint
    steps:
      - uses: actions/checkout@v2
      - uses: hadolint/hadolint-action@v2.0.0
        with:
          dockerfile: Dockerfile
