---
name: Release
'on':
  push:
    tags:
      - '*'
jobs:
  release:
    name: Create Release
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.0
      - name: Set YAAM deliverable environment variable
        run: echo "yaam-deliverable=yaam-ubuntu-20.04" >> $GITHUB_ENV
      - name: Use the value
        run: |
          echo "${{ env.yaam-deliverable }}"
      - name: Check whether all versions have been updated
        run: |
          version=$(echo "${{ github.ref }}" | sed -e "s|.*\/\(.*\)$|\1|")
          echo "Version: ${version}"
          echo "Checking README.md..."
          grep "yaam:${version}" docs/usage/DOCKER.md
      - name: Create release
        run: ./scripts/build.sh
        env:
          YAAM_DELIVERABLE: ${{ env.yaam-deliverable }}
          GITHUB_TAG: ${{ github.ref }}
          SHA512_CMD: sha512sum
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: cmd/yaam/${{ env.yaam-deliverable }}
          asset_name: ${{ env.yaam-deliverable }}
          tag: ${{ github.ref }}
      - name: Upload checksums
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: cmd/yaam/${{ env.yaam-deliverable }}.sha512.txt
          asset_name: ${{ env.yaam-deliverable }}.sha512.txt
          tag: ${{ github.ref }}
